#!/usr/bin/env python3
"""
TRUCKLY — Deliverables 22 & 23: the ML extension, and the circularity audit.

WHY THIS TASK AND NOT THE OBVIOUS ONES
--------------------------------------
Three ML tasks were considered and REJECTED as circular (Deliverable 23):

  * Fuel prediction      -- fuel is generated by a known formula. Training a
                            model to recover that formula measures nothing but
                            our own arithmetic. A high R2 would be meaningless.
  * Travel-time predict. -- durations come from a deterministic distance/speed
                            model. Same problem.
  * Feasibility predict. -- "is this match feasible?" is recoverable exactly
                            from the constraints; a classifier would just be a
                            lossy re-implementation of the filter.

The ONE task that survives is candidate PRUNING. The target is
`selected_by_optimiser` -- whether the CP-SAT solver chose this (truck, bundle)
pair. That label comes from a GLOBAL combinatorial optimisation over all trucks
competing simultaneously, and it is NOT a deterministic function of any single
candidate's features. The model therefore has something real to learn.

And the relationship is the correct one: ML SERVES the optimiser (making it
faster by shrinking the search space) rather than replacing it. The optimiser
remains the decision-maker. Truckly does not work because of ML.

The real deliverable is not the ROC-AUC. It is the PRUNING vs OPTIMALITY-GAP
curve: how much of the candidate set can be discarded before solution quality
degrades.
"""
from __future__ import annotations
import os, sys, json, time
import numpy as np
import pandas as pd
import yaml
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, HistGradientBoostingClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (precision_score, recall_score, f1_score,
                             roc_auc_score, average_precision_score,
                             confusion_matrix, brier_score_loss)

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, HERE)
from src.network import RoadNetwork
from src.data_generator import InstanceGenerator
from src.domain import CostModel
from src.matching import generate_candidates, add_competition_features
from src.optimizer import solve_assignment

TAB = os.path.join(HERE, "outputs", "tables")
RES = os.path.join(HERE, "outputs", "results")

FEATURES = ["bundle_size", "pickup_detour_km", "delivery_detour_km",
            "empty_km_avoided", "total_detour_km", "weight_ratio",
            "volume_ratio", "deadline_slack_hr", "wait_before_pickup_hr",
            "bearing_deviation_deg", "c_kb_inr", "obj_kb_inr",
            "cost_delta_vs_empty_inr", "match_score", "cost_rank_within_truck",
            "n_candidates_for_truck", "competing_trucks",
            "local_shipment_density"]


def evaluate(y, p, thr=0.5):
    yh = (p >= thr).astype(int)
    tn, fp, fn, tp = confusion_matrix(y, yh, labels=[0, 1]).ravel()
    return dict(threshold=thr, precision=precision_score(y, yh, zero_division=0),
                recall=recall_score(y, yh, zero_division=0),
                f1=f1_score(y, yh, zero_division=0),
                roc_auc=roc_auc_score(y, p), pr_auc=average_precision_score(y, p),
                brier=brier_score_loss(y, p),
                tp=int(tp), fp=int(fp), fn=int(fn), tn=int(tn))


# ---------------------------------------------------------------------------
def pruning_experiment(model, cfg, scenario="S3_high_avail", instances=range(80, 100)):
    """The deliverable that matters: prune -> re-solve -> measure the gap."""
    net = RoadNetwork(cfg); cost = CostModel(cfg); gen = InstanceGenerator(cfg, net)
    rows = []
    for inst_id in instances:
        inst = gen.generate(scenario, inst_id)
        cands, base, _ = generate_candidates(
            inst["trucks"], inst["shipments"], net, cost, inst["eps"],
            inst["params"], cfg, max_bundle=inst["params"]["max_bundle_size"],
            collect_rejects=False)
        add_competition_features(cands, inst["shipments"])
        if not cands:
            continue
        X = pd.DataFrame([c.features for c in cands])[FEATURES]
        p = model.predict_proba(X)[:, 1]

        t0 = time.perf_counter()
        full, st, ms_full, obj_full = solve_assignment(
            cands, base, inst["trucks"], inst["shipments"])
        ms_full = (time.perf_counter() - t0) * 1000

        for thr in [0.0, 0.02, 0.05, 0.10, 0.20, 0.30, 0.50, 0.70]:
            keep = [c for c, pp in zip(cands, p) if pp >= thr]
            pruned_pct = 100 * (1 - len(keep) / len(cands))
            if not keep:
                rows.append(dict(instance_id=inst_id, threshold=thr,
                                 n_candidates=len(cands), n_kept=0,
                                 pruned_pct=100.0, obj_full=obj_full,
                                 obj_pruned=None, gap_pct=np.nan,
                                 ms_full=ms_full, ms_pruned=0.0))
                continue
            t0 = time.perf_counter()
            _, st2, _, obj_p = solve_assignment(
                keep, base, inst["trucks"], inst["shipments"])
            ms_p = (time.perf_counter() - t0) * 1000
            # objective is a MINIMISATION of (cost - revenue); it can be
            # negative, so the gap is normalised by |obj_full|
            gap = (100 * (obj_p - obj_full) / abs(obj_full)
                   if obj_full not in (None, 0) and obj_p is not None else np.nan)
            rows.append(dict(instance_id=inst_id, threshold=thr,
                             n_candidates=len(cands), n_kept=len(keep),
                             pruned_pct=pruned_pct, obj_full=obj_full,
                             obj_pruned=obj_p, gap_pct=gap,
                             ms_full=ms_full, ms_pruned=ms_p))
    return pd.DataFrame(rows)


def main():
    cfg = yaml.safe_load(open(os.path.join(HERE, "config.yaml")))
    C = pd.read_csv(os.path.join(RES, "candidates_main.csv"))
    C = C.dropna(subset=FEATURES + ["selected_by_optimiser"])
    print(f"candidates: {len(C):,}   positive rate: {C.selected_by_optimiser.mean():.4f}")

    # SPLIT BY INSTANCE, never by row: candidates in the same simulated day
    # compete for the same shipments and are not independent.
    C["grp"] = C.scenario_id + "_" + C.instance_id.astype(str)
    ins = np.sort(C.instance_id.unique())
    tr_i = ins[ins < 60]; va_i = ins[(ins >= 60) & (ins < 80)]; te_i = ins[ins >= 80]
    tr = C[C.instance_id.isin(tr_i)]; va = C[C.instance_id.isin(va_i)]
    te = C[C.instance_id.isin(te_i)]
    print(f"train {len(tr):,} / val {len(va):,} / test {len(te):,} rows "
          f"({len(tr_i)}/{len(va_i)}/{len(te_i)} instances)")

    Xtr, ytr = tr[FEATURES], tr.selected_by_optimiser.values
    Xva, yva = va[FEATURES], va.selected_by_optimiser.values
    Xte, yte = te[FEATURES], te.selected_by_optimiser.values

    models = {
        "LogisticRegression": make_pipeline(
            StandardScaler(), LogisticRegression(max_iter=2000, C=1.0)),
        "RandomForest": RandomForestClassifier(
            n_estimators=300, min_samples_leaf=8, n_jobs=-1, random_state=42),
        "GradientBoosting": HistGradientBoostingClassifier(
            max_iter=350, learning_rate=0.07, random_state=42),
    }
    rows, fitted = [], {}
    for name, m in models.items():
        m.fit(Xtr, ytr); fitted[name] = m
        for split, X, y in [("validation", Xva, yva), ("test", Xte, yte)]:
            p = m.predict_proba(X)[:, 1]
            r = evaluate(y, p)
            r.update(model=name, split=split, n=len(y), positive_rate=float(y.mean()))
            rows.append(r)
    M = pd.DataFrame(rows)[["model", "split", "n", "positive_rate", "threshold",
                            "precision", "recall", "f1", "roc_auc", "pr_auc",
                            "brier", "tp", "fp", "fn", "tn"]].round(4)
    M.to_csv(os.path.join(TAB, "ml_model_comparison.csv"), index=False)
    print("\n", M.to_string(index=False))

    best = M[(M.split == "test")].sort_values("pr_auc", ascending=False).iloc[0].model
    bm = fitted[best]
    print(f"\nbest by test PR-AUC: {best}")

    # recall at operating thresholds -- recall is what matters, because a
    # pruned true positive is a lost optimal solution
    p_te = bm.predict_proba(Xte)[:, 1]
    thr_rows = [dict(**evaluate(yte, p_te, t),
                     kept_pct=round(100 * (p_te >= t).mean(), 2))
                for t in [0.02, 0.05, 0.10, 0.20, 0.30, 0.50, 0.70]]
    TH = pd.DataFrame(thr_rows).round(4)
    TH.to_csv(os.path.join(TAB, "ml_threshold_table.csv"), index=False)

    # feature importance (permutation-free: use the model's own where available)
    if hasattr(bm, "feature_importances_"):
        imp = pd.DataFrame({"feature": FEATURES,
                            "importance": bm.feature_importances_})
    else:
        from sklearn.inspection import permutation_importance
        pi = permutation_importance(bm, Xte, yte, n_repeats=5, random_state=0,
                                    scoring="average_precision")
        imp = pd.DataFrame({"feature": FEATURES, "importance": pi.importances_mean})
    imp = imp.sort_values("importance", ascending=False).round(4)
    imp.to_csv(os.path.join(TAB, "ml_feature_importance.csv"), index=False)

    # ---- THE deliverable: pruning vs optimality gap -----------------------
    print("\nrunning pruning experiment (re-solving CP-SAT per threshold)...")
    P = pruning_experiment(bm, cfg)
    P.to_csv(os.path.join(TAB, "ml_pruning_raw.csv"), index=False)
    agg = (P.groupby("threshold")
           .agg(mean_pruned_pct=("pruned_pct", "mean"),
                mean_gap_pct=("gap_pct", "mean"),
                worst_gap_pct=("gap_pct", "max"),
                instances_with_zero_gap=("gap_pct", lambda s: int((s.abs() < 1e-9).sum())),
                mean_ms_full=("ms_full", "mean"),
                mean_ms_pruned=("ms_pruned", "mean"),
                n_instances=("instance_id", "nunique"))
           .assign(speedup=lambda d: d.mean_ms_full / d.mean_ms_pruned.clip(lower=1e-9))
           .round(4).reset_index())
    agg.to_csv(os.path.join(TAB, "ml_pruning_curve.csv"), index=False)
    print("\n", agg.to_string(index=False))

    L = ["# TRUCKLY — ML Extension: Learning to Prune the Candidate Set", "",
         "## Deliverable 23 — circularity audit (what was NOT built, and why)", "",
         "| Candidate ML task | Verdict | Reason |", "|---|---|---|",
         "| Fuel-consumption prediction | **REJECTED** | fuel is generated by a "
         "known formula; a model would recover our own constant. R2 would measure "
         "nothing. |",
         "| Travel-time prediction | **REJECTED** | durations come from a "
         "deterministic distance/speed model. Same circularity. |",
         "| Feasibility prediction | **REJECTED** | exactly recoverable from the "
         "hard constraints; a classifier is a lossy re-implementation of the filter. |",
         "| **Candidate pruning (`selected_by_optimiser`)** | **BUILT** | the label "
         "comes from a global combinatorial optimisation over competing trucks and is "
         "not a function of any single candidate's features. |", "",
         "> **Truckly does not work because of machine learning.** The optimiser is "
         "the decision-maker; the classifier only shrinks the search space it works "
         "over. Removing the ML layer changes runtime, not the result.", "",
         "## Data and split", "",
         f"- {len(C):,} candidate rows, positive rate **{C.selected_by_optimiser.mean():.1%}**",
         f"- Split **by instance, never by row** ({len(tr_i)} train / {len(va_i)} "
         f"validation / {len(te_i)} test instances). Candidates in the same simulated "
         "day compete for the same shipments; a row-wise split would leak.",
         "- Accuracy is **not** reported: under this class imbalance a "
         f"trivial all-negative classifier scores {1-C.selected_by_optimiser.mean():.1%}.",
         "", "## Deliverable 22 — model comparison", "", M.to_markdown(index=False), "",
         "### Threshold sweep for the best model (" + best + ")", "",
         "Recall is the metric that matters: a pruned true positive is a lost "
         "optimal assignment.", "", TH.to_markdown(index=False), "",
         "### Feature importance", "", imp.to_markdown(index=False), "",
         "## The real result — pruning vs optimality gap", "",
         "For each test instance the CP-SAT model is solved twice: once over the full "
         "candidate set, once over the pruned set. The gap is the loss in objective "
         "value caused by pruning, normalised by |objective|.", "",
         agg.to_markdown(index=False), ""]
    open(os.path.join(TAB, "ml_report.md"), "w").write("\n".join(L))
    json.dump({"best_model": best}, open(os.path.join(TAB, "ml_best.json"), "w"))


if __name__ == "__main__":
    main()
